# This workflow builds the production web app

name: Deploy webapp to production

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'

      - name: Build
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release

      # Deploy to Github Pages
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: deploy
          FOLDER: build/web
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Automatic deployment up to {sha} to production"
