# This workflow builds the production web app

name: prod_build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: erickzanardo/flutter-gh-pages@v2
